version: '3.7'

services:
    next-app:
        image: "${DOCKER_REGISTRY}/next-app:${TAG}"
        build:
            context: .
            dockerfile: ./apps/Dockerfile
            args:
                APP: next-app
                DOCKER_REGISTRY: ${DOCKER_REGISTRY}   
                TAG: ${TAG}          

    backend:
        image: "${DOCKER_REGISTRY}/backend:${TAG}"
        build:
            context: ./backend/
            dockerfile: ./Dockerfile