version: '3.7'

services:
    frontend:
        image: "${DOCKER_REGISTRY}/pantry-frontend:${TAG}"
        build:
            context: .
            dockerfile: ./apps/Dockerfile
            args:
                APP: user-portal
                DOCKER_REGISTRY: ${DOCKER_REGISTRY}
                TAG: ${TAG}

    backend:
        image: "${DOCKER_REGISTRY}/pantry-backend:${TAG}"
        build:
            context: .
            dockerfile: ./backend/Dockerfile
