# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pantryadmin

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  BACKEND_BASE_URL: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://collectivereg.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_28d39508e5734f558fc68a409d6d0fac }}
          password: ${{ secrets.AzureAppService_ContainerPassword_807a7babf8fc4bbab3814a0bd2d77375 }}

      - name: Build and push backend container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: collectivereg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_28d39508e5734f558fc68a409d6d0fac }}/pantry-backend-dev:${{ github.sha }}
          file: ./backend/Dockerfile

      - name: Build and push frontend container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: collectivereg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e63bb1905c6a4a45b5a231dfb2e20209 }}/pantry-frontend-dev:${{ github.sha }}
          file: ./apps/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Test"
      url: ${{ steps.frontend-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Backend to Azure Web App
        id: backend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "pantrybackend-dev"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b238d802ac8645e6b65a5edde468d12d }}
          images: "collectivereg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_28d39508e5734f558fc68a409d6d0fac }}/pantry-backend-dev:${{ github.sha }}"

      - name: Deploy Frontend to Azure Web App
        id: frontend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "pantryfrontend-dev"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_3d252031ecc64559a923899a336cd451 }}
          images: "collectivereg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e63bb1905c6a4a45b5a231dfb2e20209 }}/pantry-frontend-dev:${{ github.sha }}"
