name: Build and Push Docker image to ACR

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      acrContainerUsername:
        required: true
      acrContainerPassword:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://collectivereg.azurecr.io/
          username: ${{ secrets.acrContainerUsername }}
          password: ${{ secrets.acrContainerPassword }}

      - name: Build and push backend container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: collectivereg.azurecr.io/${{ secrets.acrContainerUsername }}/pantry-backend-${{ inputs.environment }}:${{ github.sha }}
          file: ./backend/Dockerfile

      - name: Build and push frontend container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: collectivereg.azurecr.io/${{ secrets.acrContainerUsername }}/pantry-frontend-${{ inputs.environment }}:${{ github.sha }}
          file: ./apps/Dockerfile