name: Build and deploy Node.js app to Azure Web App - pantryadmin

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BACKEND_BASE_URL: http://localhost:3000


jobs:
  build:
    uses: ./.github/workflows/dockerbuild.yml
    with:
      environment: Production
      frontendContainerName: pantry-frontend
      backendContainerName: pantry-backend
    secrets:
      acrContainerUsername: ${{ secrets.AzureAppService_ContainerUsername_28d39508e5734f558fc68a409d6d0fac }}
      acrContainerPassword: ${{ secrets.AzureAppService_ContainerPassword_807a7babf8fc4bbab3814a0bd2d77375 }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploywebapps.yml
    with:
      environment: prod
      frontendContainerName: pantry-frontend
      backendContainerName: pantry-backend
      frontendAppName: pantryfrontend
      backendAppName: pantryadmin-docker
    secrets:
      backendPublishProfile: ${{ secrets.AzureAppService_PublishProfile_d7e475cd12ae435193e3f0efff1d8394 }}
      frontendPublishProfile: ${{ secrets.AzureAppService_PublishProfile_4d2ccba4715b4bfe9af97028f357c793 }}
      acrContainerUsername: ${{ secrets.AzureAppService_ContainerUsername_28d39508e5734f558fc68a409d6d0fac }}