name: Test build

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@main
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn

      - name: Turbo Run Build
        run: BACKEND_BASE_URL=http://localhost:3000 yarn turbo run build
